// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

import './ColorTile.scss';
;

function AppColorTile$appColorTile(Props) {
  var colorHex = Props.colorHex;
  var colorTileIndex = Props.colorTileIndex;
  var reshuffleSingle = Props.reshuffleSingle;
  return React.createElement("div", {
              className: "color-tile-outer-container"
            }, React.createElement("div", {
                  className: "color-tile-inner-container"
                }, React.createElement("div", {
                      className: "color-tile",
                      style: {
                        backgroundColor: colorHex
                      }
                    }), React.createElement("div", {
                      className: "color-code",
                      onClick: (function (param) {
                          Curry._1(reshuffleSingle, colorTileIndex);
                        })
                    }, React.createElement("div", undefined, React.createElement("span", undefined, colorHex)))));
}

var appColorTile = AppColorTile$appColorTile;

export {
  appColorTile ,
}
/*  Not a pure module */
