// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './AppHeader.scss';
;

function AppHeader(Props) {
  var name = Props.name;
  return React.createElement("div", {
              className: "app-header-container"
            }, React.createElement("h1", {
                  className: "user-name"
                }, name), React.createElement("img", {
                  src: "/icons/divertise-asia.webp"
                }));
}

var make = AppHeader;

export {
  make ,
}
/*  Not a pure module */
